/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE
 * file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package net.ssehub.comani.analysis.variabilitychange.tests;

import java.io.File;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import net.ssehub.comani.analysis.variabilitychange.tests.coman.ArtificialCommitsTests;
import net.ssehub.comani.analysis.variabilitychange.tests.coman.CorebootCommitsTests;
import net.ssehub.comani.analysis.variabilitychange.tests.coman.DebugCommitsTests;
import net.ssehub.comani.analysis.variabilitychange.tests.coman.LinuxCommitsTests;
import net.ssehub.comani.analysis.variabilitychange.tests.coman.LinuxMergeCommitsTests;

/**
 * Definition of this test suite.
 */
@RunWith(Suite.class)
@SuiteClasses({
    // The following classes contain tests that were initial used to test the ComAn tool-set
    ArtificialCommitsTests.class,
    DebugCommitsTests.class,
    CorebootCommitsTests.class,
    LinuxCommitsTests.class,
    LinuxMergeCommitsTests.class,
    // The following classes contain tests that use commits as extracted by the GitCommitExtractor
    net.ssehub.comani.analysis.variabilitychange.tests.comani.CorebootCommitsTests.class,
    net.ssehub.comani.analysis.variabilitychange.tests.comani.LinuxCommitsTests.class,
    net.ssehub.comani.analysis.variabilitychange.tests.comani.LinuxMergeCommitsTests.class
    })

/**
 * This class summarizes all individual test classes into a single test suite.
 * 
 * @author Christian Kroeher
 *
 */
public class AllTests {
    
    /**
     * The {@link File} denoting the root directory in which the test input data, like commits and expected value
     * tables, are located. Further sub-directories exist for structuring the data for the individual test classes.
     */
    public static final File TESTDATA_DIRECTORY = new File("./testdata");
    
    /**
     * The {@link File} denoting the directory in which the analyzer saves its analysis results. This directory should
     * always be empty. Files in this directory will be deleted during {@link AbstractCommitsTests#tearDown(String)}.
     */
    public static final File TESTOUTPUT_DIRECTORY = new File("./testoutput");
    
    /**
     * The name and file extension of the result file generated by the analyzer.
     */
    public static final String ANALYZER_RESULTS_FILE = "VariabilityChangeAnalyzer_Results.tsv";
    
    /**
     * The name and file extension of the unanalyzed commits summary file generated by the analyzer.
     */
    public static final String ANALYZER_UNANALYZED_COMMITS_SUMMARY_FILE = "VariabilityChangeAnalyzer_Unanalyzed.txt";
    
}
